### ISSUE TITLE
Brainstorming the next tasks

### ISSUE THREAD

**Issue by vmadincea** [rtodea/browser-tools#10]
First, we need to decide on what the user can do in the app.

- The user can upload a csv, that is done.
- The user can preview the csv file and contents, at least in a simple table for now.
- The user can create a workflow of actions that can be applied in a particular order. 
This workflow should be stored internally maybe in a json-like object of array of actions. That workflow schema can then be saved and re-applied on future similar files on the PAID PLAN.
The order is important because maybe first the user would like to process two columns that are dependent on each other.
- Possible actions: rename header, process a column.

**Comment by robert-at-mai** [comment]
Let's think about the following:

1. ad support
2. overall look & feel of the website (some free template that we like)

**Comment by rtodea** [comment]
Let's think about the following:

1. ad support
2. overall look & feel of the website (some free template that we like)
