### ISSUE TITLE
Add access for second team member in the Vercel dashboard

### ISSUE THREAD

**Issue by rtodea** [rtodea/browser-tools#5]
To allow management dashboard to be accessible to another account (beside the one that started the integration, i.e. `rtodea`), we need to upgrade to Pro.

> https://vercel.com/docs/accounts/plans#plans-comparison

We have to options:

1. upgrade and add 20 USD/month /user
2. migrate this project to a common Github account (e.g. `browser-tools-github`)

I would opt for (2).
Pros:
1. free
2. keep accounts isolated
3. we can also create a Google Drive account (`browser-tools-google@gmail.com`), etc.

Cons:
1. hassle with re-using accounts

@vmadincea, what do you think?

**Comment by vmadincea** [comment]
I don't think we need the management dashboard until we go into production. And even then, for a while, it's alright only for one user to see the dashboard.
So I would choose solution 1 because it's the simplest and can be deferred.

**Comment by robert-at-mai** [comment]
I think it's 20 dollars each, so 40 dollars in total.
